name: website-deploy
on:
  push:
    branches:
      - 'master'
permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  Job:
    runs-on: windows-latest
    steps:
      - name: Convert Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: html/index.html
          github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
