name: render readme

# Controls when the action will run
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Test Converts markdown text to HTML
        uses: ./
        with:
          source: README-zh.md
          output: coverage/action.html
          style: 'body { margin: 0; }'
          github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌐</text></svg>